;PRACTICA - SEGUNDO EXAMEN PARCIAL
;CHRISTIAN GEOVANY MUNOZ RODRIGUEZ
;28 DE OCTUBRE DEL 2021

ORG 0100H               ;CS:IP

MOV AH, 0               ;CONFIGURACION DE VIDEO
MOV AL, 00H             ;40X25 COLORES
INT 10H

;MACROS

;IMPRIMIR CADENA
IMPRIMIR MACRO MENSAJE
    MOV AH, 09H
    LEA DX, MENSAJE
    INT 21H
ENDM

;INGRESAR CARACTER POR TECLADO (EN ASCII)
INGRESO MACRO
    MOV AH, 1
    INT 21H
ENDM

;SALTO DE LINEA Y RETORNO DE CARRO CON INTERRUPCION 10
SALTO_LINEA MACRO 
    MOV AH, 0EH
    MOV AL, 10          
    INT 10H
    MOV AH, 0EH         
    MOV AL, 13          
    INT 10H
ENDM

;CONVERSION DE PARA RESULTADO DE DOS DIGITOS A FORMATO ASCII
CONVERSION MACRO
    MOV AX, CX  ;MUEVE EL RESULTADO DE LA SUMA A AX PARA REALIZAR LA DIVISION
    MOV BL, 10  ;DEFINIMOS EL DIVISOR COMO 10 PARA OBTENER DECENAS
    DIV BL      ;SE REALIZA DIVISION. EL RESIDUO SON LAS UNIDADES
    MOV CH,AH   ;MOVEMOS EL RESIDUO A OTRO REGISTRO
    MOV AH, 0EH
    ADD AL, 30H
    INT 10H     ;IMPRIMIMOS DIGITO DE LAS DECENAS
    MOV AH, 0EH
    MOV AL, CH
    ADD AL, 30H
    INT 10H     ;IMPRIMIMOS RESIDUO (UNIDADES)
ENDM

;PROGRAMA PRINCIPAL

IMPRIMIR msje
INGRESO

SUB AL,30H ;CONVIERTE PRIMER DIGITO DE ASCII A HEX
MOV CX,10  ;DEFINE ITERACIONES PARA MULTIPLICAR PRIMER DIGITO 
MULTIPLICACION:
    ADD BL,AL
    LOOP MULTIPLICACION ;MULTIPLICA PRIMER DIGITO POR 10 PARA DECENAS 

INGRESO 

SUB AL,30H               
ADD BL, AL ;SUMA SEGUNDO DIGITO PARA LAS UNIDADES
              
SALTO_LINEA
IMPRIMIR msje2
INGRESO

SUB AL,30H
MOV CX,10
MULTIPLICACION_2:
    ADD BH,AL
    LOOP MULTIPLICACION_2
 
INGRESO

SUB AL, 30H
ADD BH, AL

SALTO_LINEA

ADD BL,BH ;HACE LA SUMA DE LOS DOS NUMEROS EN EL REGISTRO L
MOV BH,0  ;PONE EL REGISTRO BH EN 0 PARA QUE BX QUEDE BIEN REPRESENTADO EN 32 BITS
              
IMPRIMIR msje3

MOV CX,BX ;MUEVE BX A CX PARA UTILIZAR LOS REGISTROS DE BX EN LA DIVISION

CONVERSION



RET

msje db "INGRESE A: $"
msje2 db "INGRESE B: $"
msje3 db "A  +  B  = $"